name:                ordning
version:             0.1.0.0
github:              "mhcurylo/ordning"
license:             MIT
author:              "Mateusz Curylo"
maintainer:          "mhcurylo@gmail.com"
copyright:           "2019 Mateusz Curylo"

extra-source-files:
- README.md
- ChangeLog.md

default-extensions: 
- AllowAmbiguousTypes 
- DataKinds
- DefaultSignatures
- DeriveGeneric
- DeriveAnyClass
- EmptyCase 
- FlexibleInstances
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving 
- InstanceSigs 
- KindSignatures
- MultiParamTypeClasses
- RankNTypes 
- ScopedTypeVariables
- StandaloneDeriving 
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeInType
- TypeOperators
- UndecidableInstances 
- LambdaCase
- TypeApplications
- TemplateHaskell
#
# Metadata used when publishing your package
synopsis: Terminal pomodoro timer with sound 
category: Productivity tool

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mhcurylo/ordning#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options: -Wall 
  dependencies:
    - optparse-applicative  
    - ansi-terminal
    - typelits-witnesses
    - comonad
    - stm
    - mtl
    - OpenAL
    - ALUT

executables:
  ordning:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ordning

tests:
  ordning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ordning
    - hspec
    - QuickCheck
