name:                ordning
version:             0.1.0.0
github:              "mhcurylo/ordning"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

default-extensions: 
- DataKinds
- DefaultSignatures
- DeriveGeneric
- DeriveAnyClass
- FlexibleInstances
- FlexibleContexts
- GADTs
- KindSignatures
- MultiParamTypeClasses
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeInType
- TypeOperators
- LambdaCase
- TypeApplications
- TemplateHaskell
#
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mhcurylo/ordning#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - optparse-applicative  
    - ansi-terminal
    - typelits-witnesses
    - comonad
    - stm
    - OpenAL
    - ALUT

executables:
  ordning:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ordning

tests:
  ordning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ordning
    - hspec
    - QuickCheck
